CREATE TABLE PORTFOLIO (
    PORTFOLIO_ID INT IDENTITY not null,
    BALANCE DOUBLE,
    VERSION INTEGER,
    PRIMARY KEY (PORTFOLIO_ID)
);
CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT IDENTITY not null,
    ACCOUNT_TYPE CHARACTER(1),
    BALANCE DOUBLE,
    VERSION INTEGER,
    PORTFOLIO_ID INTEGER,
    PRIMARY KEY (ACCOUNT_ID)
);
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCNT_PFOLIO_FK  FOREIGN KEY(PORTFOLIO_ID) REFERENCES PORTFOLIO(PORTFOLIO_ID);


CREATE TABLE ASSET (
    ASSET_ID INT IDENTITY not null,
    PORTFOLIO_ID INTEGER,
    PRIMARY KEY (ASSET_ID)
);

ALTER TABLE ASSET ADD CONSTRAINT ASSET_PFOLIO_FK FOREIGN KEY(PORTFOLIO_ID) REFERENCES PORTFOLIO(PORTFOLIO_ID);


CREATE TABLE USER_ACCOUNT (
    USER_ID INT IDENTITY not null,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE USER_ACCOUNT_ACCOUNT (
    USER_ID INT IDENTITY not null,
    ACCOUNT_ID INTEGER not null,
);

ALTER TABLE USER_ACCOUNT_ACCOUNT ADD CONSTRAINT FK1 FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);
ALTER TABLE USER_ACCOUNT_ACCOUNT ADD CONSTRAINT FK2 FOREIGN KEY(USER_ID) REFERENCES USER_ACCOUNT(USER_ID);

ALTER TABLE USER_ACCOUNT ADD RATE DOUBLE;